# 服务器端口号
server:
  port: 80

# 注册用应用程序名称
spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: false    # true 表示在注册中心注册自己，默认为true
#    fetch-registry: true          # true 从EurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配置ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka   # 集群版

# 设置feign客户端超时时间(OpenFeign默认支持ribbon,默认时间为1秒)
ribbon:
  ReadTimeout: 5000        # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000     # 指的是建立连接所用的时间,适用于网络状态正常的情况下,两端连接所用的时间

logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.atguigu.springcloud.service.PaymentFeignService: debug
