# 服务器端口号
server:
  port: 8001

spring:
  application:
    name: cloud-provider-hystrix-payment # spring应用程序名称（服务名称）

eureka:
  client:
    register-with-eureka: true    # true 表示在注册中心注册自己，默认为true
    fetch-registry: true          # true 从EurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配置ribbon使用负载均衡
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka   # 集群版
      defaultZone: http://eureka7001.com:7001/eureka   # 单机版