# 服务器端口号
server:
  port: 80

eureka:
  client:
    register-with-eureka: false    # true 表示在注册中心注册自己，默认为true
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka   # 集群版
      defaultZone: http://eureka7001.com:7001/eureka   # 单机版

# 设置feign客户端超时时间(OpenFeign默认支持ribbon,默认时间为1秒)
ribbon:
  ReadTimeout: 5000        # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000     # 指的是建立连接所用的时间,适用于网络状态正常的情况下,两端连接所用的时间

feign:
  hystrix:
    enabled: true  # 如果是真，开启熔断机制